# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: survey.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'survey.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csurvey.proto\x12\x06survey\"*\n\x06\x41nswer\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\"6\n\x0cSurveyResult\x12\x15\n\rtotal_answers\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2H\n\rSurveyService\x12\x37\n\rSubmitAnswers\x12\x0e.survey.Answer\x1a\x14.survey.SurveyResult(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'survey_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANSWER']._serialized_start=24
  _globals['_ANSWER']._serialized_end=66
  _globals['_SURVEYRESULT']._serialized_start=68
  _globals['_SURVEYRESULT']._serialized_end=122
  _globals['_SURVEYSERVICE']._serialized_start=124
  _globals['_SURVEYSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
