# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15message_service.proto\x12\x07message\"\x1d\n\x0c\x45mailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"!\n\x0fPasswordRequest\x12\x0e\n\x06length\x18\x01 \x01(\x05\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2\xc0\x01\n\x0eMessageService\x12\x35\n\tSubscribe\x12\x15.message.EmailRequest\x1a\x11.message.Response\x12?\n\x10GeneratePassword\x12\x18.message.PasswordRequest\x1a\x11.message.Response\x12\x36\n\x0b\x43ountVowels\x12\x14.message.TextRequest\x1a\x11.message.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILREQUEST']._serialized_start=34
  _globals['_EMAILREQUEST']._serialized_end=63
  _globals['_PASSWORDREQUEST']._serialized_start=65
  _globals['_PASSWORDREQUEST']._serialized_end=98
  _globals['_TEXTREQUEST']._serialized_start=100
  _globals['_TEXTREQUEST']._serialized_end=127
  _globals['_RESPONSE']._serialized_start=129
  _globals['_RESPONSE']._serialized_end=155
  _globals['_MESSAGESERVICE']._serialized_start=158
  _globals['_MESSAGESERVICE']._serialized_end=350
# @@protoc_insertion_point(module_scope)
